MLBTeams = {
    "BAL": {
        "league": "AL",
        "division": "E",
        "active": True,
        "team_name": "Orioles",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/BAL.png&h=60",
    },
    "BOS": {
        "league": "AL",
        "division": "E",
        "active": True,
        "team_name": "Red Sox",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/BOS.png&h=60",
    },
    "NYA": {
        "league": "AL",
        "division": "E",
        "active": True,
        "team_name": "Yankees",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/NYY.png&h=60",
    },
    "TBA": {
        "league": "AL",
        "division": "E",
        "active": True,
        "team_name": "Rays",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/tb.png&h=60",
    },
    "TOR": {
        "league": "AL",
        "division": "E",
        "active": True,
        "team_name": "Blue Jays",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/TOR.png&h=60",
    },
    "CHA": {
        "league": "AL",
        "division": "C",
        "active": True,
        "team_name": "White Sox",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/CHW.png&h=60",
    },
    "CLE": {
        "league": "AL",
        "division": "C",
        "active": True,
        "team_name": "Guardians",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/CLE.png&h=60",
    },
    "DET": {
        "league": "AL",
        "division": "C",
        "active": True,
        "team_name": "Tigers",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/DET.png&h=60",
    },
    "KCA": {
        "league": "AL",
        "division": "C",
        "active": True,
        "team_name": "Royals",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/KC.png&h=60",
    },
    "MIN": {
        "league": "AL",
        "division": "C",
        "active": True,
        "team_name": "Twins",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/MIN.png&h=60",
    },
    "HOU": {
        "league": "AL",
        "division": "W",
        "active": True,
        "team_name": "Astros",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/HOU.png&h=60",
    },
    "ANA": {
        "league": "AL",
        "division": "W",
        "active": True,
        "team_name": "Angels",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/LAA.png&h=60",
    },
    "OAK": {
        "league": "AL",
        "division": "W",
        "active": True,
        "team_name": "Athletics",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/OAK.png&h=60",
    },
    "SEA": {
        "league": "AL",
        "division": "W",
        "active": True,
        "team_name": "Mariners",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/SEA.png&h=60",
    },
    "TEX": {
        "league": "AL",
        "division": "W",
        "active": True,
        "team_name": "Rangers",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/TEX.png&h=60",
    },
    "ATL": {
        "league": "NL",
        "division": "E",
        "active": True,
        "team_name": "Braves",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/ATL.png&h=60",
    },
    "FLO": {
        "league": "NL",
        "division": "E",
        "active": False,
        "team_name": "Marlins",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/MIA.png&h=60",
    },
    "MIA": {
        "league": "NL",
        "division": "E",
        "active": True,
        "team_name": "Marlins",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/MIA.png&h=60",
    },
    "NYN": {
        "league": "NL",
        "division": "E",
        "active": True,
        "team_name": "Mets",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/NYM.png&h=60",
    },
    "PHI": {
        "league": "NL",
        "division": "E",
        "active": True,
        "team_name": "Phillies",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/PHI.png&h=60",
    },
    "WAS": {
        "league": "NL",
        "division": "E",
        "active": True,
        "team_name": "Nationals",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/WSH.png&h=60",
    },
    "CHN": {
        "league": "NL",
        "division": "C",
        "active": True,
        "team_name": "Cubs",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/CHC.png&h=60",
    },
    "CIN": {
        "league": "NL",
        "division": "C",
        "active": True,
        "team_name": "Reds",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/CIN.png&h=60",
    },
    "MIL": {
        "league": "NL",
        "division": "C",
        "active": True,
        "team_name": "Brewers",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/MIL.png&h=60",
    },
    "PIT": {
        "league": "NL",
        "division": "C",
        "active": True,
        "team_name": "Pirates",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/PIT.png&h=60",
    },
    "SLN": {
        "league": "NL",
        "division": "C",
        "active": True,
        "team_name": "Cardinals",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/STL.png&h=60",
    },
    "ARI": {
        "league": "NL",
        "division": "W",
        "active": True,
        "team_name": "Diamondbacks",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/ARI.png&h=60",
    },
    "COL": {
        "league": "NL",
        "division": "W",
        "active": True,
        "team_name": "Rockies",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/COL.png&h=60",
    },
    "LAN": {
        "league": "NL",
        "division": "W",
        "active": True,
        "team_name": "Dodgers",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/LAD.png&h=60",
    },
    "SDN": {
        "league": "NL",
        "division": "W",
        "active": True,
        "team_name": "Padres",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/SD.png&h=60",
    },
    "SFN": {
        "league": "NL",
        "division": "W",
        "active": True,
        "team_name": "Giants",
        "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/scoreboard/SF.png&h=60",
    },
}
